"""new-cols

Revision ID: 4ffbfe3a4053
Revises: 8a0ffe2165ae
Create Date: 2025-05-14 00:17:11.006795

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ffbfe3a4053'
down_revision = '8a0ffe2165ae'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('user_courses', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('user_courses', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('user_courses', sa.Column('is_audit', sa.Boolean(), nullable=True))
    op.add_column('user_specialisations', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('user_specialisations', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('user_specialisations', sa.Column('is_audit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_specialisations', 'is_audit')
    op.drop_column('user_specialisations', 'completed_at')
    op.drop_column('user_specialisations', 'completed')
    op.drop_column('user_courses', 'is_audit')
    op.drop_column('user_courses', 'completed_at')
    op.drop_column('user_courses', 'completed')
