"""new-tab

Revision ID: 76427f29f0f7
Revises: 4ffbfe3a4053
Create Date: 2025-05-14 10:41:04.099613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76427f29f0f7'
down_revision = '4ffbfe3a4053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('content_url', sa.String(length=255), nullable=False),
    sa.Column('content_data', sa.JSON(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_contents_id'), 'course_contents', ['id'], unique=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_contents_id'), table_name='course_contents')
    op.drop_table('course_contents')
    # ### end Alembic commands ###
