"""spec-cols

Revision ID: 8a0ffe2165ae
Revises: f733ec8a472c
Create Date: 2025-05-11 16:26:19.045867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a0ffe2165ae'
down_revision = 'f733ec8a472c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('specialisations', sa.Column('data', sa.JSON(), nullable=True))


def downgrade():
    op.drop_column('specialisations', 'data')
    op.drop_column('courses', 'data')
